apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8sdc-prometheus
  #namespace: {{ .namespace }}
  namespace: k8sdc-system
  labels:
    app: k8sdc-prometheus
    heritage: k8sdc
spec:
  rules:
  - host: prometheus.k8sdc.io
    http:
      paths:
      - backend:
          serviceName: k8sdc-prometheus
          servicePort: 9090
