apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdc-prometheus
  #namespace: {{ .namespace }}
  namespace: k8sdc-system
  labels:
    app: k8sdc-prometheus
    heritage: k8sdc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k8sdc-prometheus
  strategy: {'type': 'RollingUpdate'}
  template:
    metadata:
      name: k8sdc-prometheus
      labels:
        app: k8sdc-prometheus
    spec:
      containers:
      - name: k8sdc-prometheus
        image: quay.io/coreos/prometheus:0.19.2
        # env:
        #   - name:  NODE_ENV
        #     value: production
        args:
          - '-storage.local.retention=96h'
          - '-storage.local.memory-chunks=800000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
          - name: http
            containerPort: 9090
            protocol: TCP
        volumeMounts:
          - name: k8sdc-prometheus
            mountPath: /prometheus/
          - name: k8sdc-prometheus-configmap
            mountPath: /etc/prometheus/
        resources:
          limits:
            cpu: 1500m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        # livenessProbe:
        #   httpGet:
        #     host: 127.0.0.1
        #     path: /
        #     port: 2368
        #     httpHeaders:
        #     - name: User-Agent
        #       value: kubernetes
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 1
      volumes:
        - name: k8sdc-prometheus
          rbd:
            monitors:
              - 192.168.1.211
              - 192.168.1.213
              - 192.168.1.215
            pool: k8sdc-system
            image: k8sdc-prometheus
            user: admin
            secretRef:
              name: ceph-secret
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: ext4
            readOnly: false
          # hostPath: 
          #   path: /var/lib/k8sdc-prometheus/
        - name: k8sdc-prometheus-configmap
          configMap:
            name: k8sdc-prometheus
        
