apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8sdc-node-exporter
  namespace: k8sdc-system
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
      hostNetwork: true
      hostPID: true