apiVersion: v1
kind: Service
metadata:
  name: k8sdc-prom-node-exporter
  namespace: k8sdc-system
  #namespace: {{ .namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: k8sdc-prom-node-exporter
    heritage: k8sdc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: k8sdc-prom-node-exporter
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  
  