apiVersion: v1
kind: Service
metadata:
  name: k8sdc-prometheus
  namespace: {{ .namespace }}
  labels:
    app: k8sdc-prometheus
    heritage: k8sdc
spec:
  selector:
    app: k8sdc-prometheus
  ports:
  - name: http
    port: 9090
    targetPort: http
    protocol: TCP