apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdc-grafana
  namespace: k8sdc-system
  labels:
    app: k8sdc-grafana
    heritage: k8sdc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k8sdc-grafana
  strategy: {'type': 'RollingUpdate'}
  template:
    metadata:
      name: k8sdc-grafana
      labels:
        app: k8sdc-grafana
    spec:
      containers:
      - name: k8sdc-grafana
        image: grafana/grafana
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 800m
            memory: 800Mi
        # livenessProbe:
        #   httpGet:
        #     host: 127.0.0.1
        #     path: /
        #     port: 2368
        #     httpHeaders:
        #     - name: User-Agent
        #       value: kubernetes
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 1

        
