apiVersion: batch/v1
kind: Job
metadata:
  name: k8sdc-opendj-job
  namespace: k8sdc-system
spec:
  template:
    metadata:
      name: k8sdc-opendj-job
    spec:
      hostNetwork: true
      containers:
      - name: k8sdc-opendj-job
        image: ceph/daemon:tag-build-master-infernalis-centos-7
        command:
          - /usr/bin/rbd
        args:
          - create 
          - --size
          - "300" 
          - k8sdc-system/k8sdc-opendj
        volumeMounts:
          - name: etc
            mountPath: /etc/ceph
          - name: var
            mountPath: /var/lib/ceph
      restartPolicy: Never
      volumes:
        - name: etc
          hostPath:
            path: /etc/ceph
        - name: var
          hostPath:
            path: /var/lib/ceph