kind: ReplicationController
apiVersion: v1
metadata:
  name: kubernetes-cockpit
  labels:
    name: kubernetes-cockpit
spec:
  replicas: 1
  selector:
    name: kubernetes-cockpit
  template:
    metadata:
      labels:
        name: kubernetes-cockpit
    spec:
      containers:
        - name: kubernetes-cockpit
          image: cockpit/kubernetes:latest
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: KUBE_INSECURE
              value: "false"

