apiVersion: v1
kind: Service
metadata:
  name: k8sdc-keycloak
  #namespace: {{ .namespace }}
  namespace: k8sdc-system
  labels:
    app: k8sdc-keycloak
    heritage: k8sdc
spec:
  selector:
    app: k8sdc-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP